### ISSUE TITLE
Failed to connect to MongoDB - wrong port?

### ISSUE THREAD

**Issue by brichardson1991** [Noah-Huppert/discord-azure-boot#2]
I've tried multiple times to get this to work. I can get both the bot and the db container up and running but the bot fails to connect to the DB it tries to connect on 29017 for some reason. 

Yet the documentation and the compose file for the DB state 27017. When attempting to change the config.ts file to reflect 27017 and recreate it, i still can see attempts to connect to 29017 in the docker logs. 

`2022-02-03T22:44:36.616172915Z { message: 'trying to authenticate with azure', level: 'info' }
2022-02-03T22:44:37.144898232Z { message: 'authenticated with azure', level: 'info' }
2022-02-03T22:44:37.370092309Z { message: 'trying to connect to mongodb', level: 'info' }
2022-02-03T22:45:07.393564754Z {
2022-02-03T22:45:07.393654542Z   error: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:29017
2022-02-03T22:45:07.393679956Z       at Timeout._onTimeout (/opt/discord-azure-bot/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
2022-02-03T22:45:07.393692490Z       at listOnTimeout (node:internal/timers:557:17)
2022-02-03T22:45:07.393703455Z       at processTimers (node:internal/timers:500:7) {
2022-02-03T22:45:07.393714538Z     reason: TopologyDescription {
2022-02-03T22:45:07.393724893Z       type: 'Single',
2022-02-03T22:45:07.393737595Z       setName: null,
2022-02-03T22:45:07.393749899Z       maxSetVersion: null,
2022-02-03T22:45:07.393760073Z       maxElectionId: null,
2022-02-03T22:45:07.393769539Z       servers: Map(1) {
2022-02-03T22:45:07.393779900Z         '127.0.0.1:29017' => ServerDescription {
2022-02-03T22:45:07.393788843Z           address: '127.0.0.1:29017',
2022-02-03T22:45:07.393794470Z           error: Error: connect ECONNREFUSED 127.0.0.1:29017
2022-02-03T22:45:07.393799795Z               at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
2022-02-03T22:45:07.393826592Z             name: 'MongoNetworkError'
2022-02-03T22:45:07.393846486Z           },
2022-02-03T22:45:07.393877730Z           roundTripTime: -1,
2022-02-03T22:45:07.393888162Z           lastUpdateTime: 18949995,
2022-02-03T22:45:07.393898145Z           lastWriteDate: null,
2022-02-03T22:45:07.393907489Z           opTime: null,
2022-02-03T22:45:07.393913417Z           type: 'Unknown',
2022-02-03T22:45:07.393918630Z           topologyVersion: undefined,
2022-02-03T22:45:07.393936422Z           minWireVersion: 0,
2022-02-03T22:45:07.393950905Z           maxWireVersion: 0,
2022-02-03T22:45:07.393968964Z           hosts: [],
2022-02-03T22:45:07.394001419Z           passives: [],
2022-02-03T22:45:07.394018865Z           arbiters: [],
2022-02-03T22:45:07.394028863Z           tags: []
2022-02-03T22:45:07.394038938Z         }
2022-02-03T22:45:07.394046837Z       },
2022-02-03T22:45:07.394052168Z       stale: false,
2022-02-03T22:45:07.394057196Z       compatible: true,
2022-02-03T22:45:07.394062168Z       compatibilityError: null,
2022-02-03T22:45:07.394083508Z       logicalSessionTimeoutMinutes: null,
2022-02-03T22:45:07.394100566Z       heartbeatFrequencyMS: 10000,
2022-02-03T22:45:07.394167118Z       localThresholdMS: 15,
2022-02-03T22:45:07.394183798Z       commonWireVersion: null
2022-02-03T22:45:07.394194124Z     }
2022-02-03T22:45:07.394203029Z   },
2022-02-03T22:45:07.394212715Z   level: 'error',
2022-02-03T22:45:07.394222495Z   message: 'failed to run main'
2022-02-03T22:45:07.394232081Z }`

**Comment by brichardson1991** [comment]
So after managing to attach a shell terminal to the container I edited my config.js and config.ts to match my local config files and it now connects to the right port but it now gives authentication errors.

```
`{ message: 'trying to authenticate with azure', level: 'info' }
{ message: 'authenticated with azure', level: 'info' }
{ message: 'trying to connect to mongodb', level: 'info' }
{
  error: MongoError: Authentication failed.
      at MessageStream.messageHandler (/opt/discord-azure-bot/node_modules/mongodb/lib/cmap/connection.js:268:20)
      at MessageStream.emit (node:events:390:28)
      at processIncomingData (/opt/discord-azure-bot/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (/opt/discord-azure-bot/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
      at writeOrBuffer (node:internal/streams/writable:389:12)
      at _write (node:internal/streams/writable:330:10)
      at MessageStream.Writable.write (node:internal/streams/writable:334:10)
      at Socket.ondata (node:internal/streams/readable:754:22)
      at Socket.emit (node:events:390:28)
      at addChunk (node:internal/streams/readable:315:12) {
    ok: 0,
    code: 18,
    codeName: 'AuthenticationFailed'
  },
  level: 'error',
  message: 'failed to run main'
}
```

**Comment by brichardson1991** [comment]
After changing the connection string to 

`	  connectionURI: "mongodb://mongo:27017",`

it now connects successfully.

**Comment by catvec** [comment]
@brichardson1991 Oh shoot! Sorry I didn't get notifications for this. Glad you figured it out and thanks for using the project 😃
